# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    # build_app("scheme": "Ant")
    xcodebuild(
      archive: true,
      archive_path: "./build-dir/MyApp.xcarchive",
      scheme:"Ant",
      build_settings:{
        "CODE_SIGN_STYLE" => "Manual",
        "PRODUCT_BUNDLE_IDENTIFIER" => "com.wolaibang.maomaotads",
        "DEVELOPMENT_TEAM" => "T8SDZM6J7S",
        "PROVISIONING_PROFILE_SPECIFIER" => "2e42fe36-7a5b-4e4d-8939-3ceb50f5abd1"
      }
    )

  end
end
